version: 0.1

phases:
  build:
    commands:
      - echo Entered to the build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/reviewia.jar
  discard-paths: yes